[workspace]
members = [
    "crates/api/kms",
    "crates/api/kms-init",
    "crates/api/kms-test",
    "crates/api/merchant",
    "crates/api/rks",
    "crates/api/wallet",
    "crates/blockchain/tx-indexer-evm",
    "crates/blockchain/tx-parser-evm",
    "crates/lib/app-config",
    "crates/lib/crypto",
]
resolver = "2"

[profile.release]
strip = "symbols"
lto = "fat"
