[package]
name = "api-kms"
version = "1.0.1"
edition = "2024"

[dependencies]
thiserror = "=2.0.16"
tracing = "=0.1.41"
tracing-subscriber = { version = "=0.3.19", features = ["fmt", "env-filter"] }
ulid = { version = "=1.2.1" }
zeroize = { version = "=1.8.1" }
chacha20poly1305 = { version = "=0.11.0-rc.1", features = ["alloc", "os_rng", "zeroize"] }
cpay-proto = { git = "https://github.com/cpay-dev/proto-rs", rev = "1150db9abe4739c55f8234eaaf5759c5e99b75fa" }
tokio = { version = "=1.47.1", features = ["rt-multi-thread", "macros", "rt", "signal"] }
tonic = { version = "=0.14.2", features = ["transport"] }
tokio-stream = "=0.1.17"
serde = { version = "=1.0.226", features = ["derive"] }
serde_json = "=1.0.145"
rustls = { version = "=0.23.31", default-features = false }
rustls-tokio-postgres = { version = "=0.1.2" }
tokio-postgres = { version = "=0.7.13" }
postgres-types = { version = "=0.2.9", features = ["derive"] }
lib-crypto = { path = "../../lib/crypto" }
app-config = { path = "../../lib/app-config" }
