[package]
name = "api-merchant"
version = "1.0.1"
edition = "2024"

[dependencies]
tokio = { version = "=1.47.1", features = ["rt-multi-thread", "macros", "rt", "signal"] }
axum = { version = "=0.8.4", features = ["http2"] }
thiserror = "=2.0.16"
tracing = "=0.1.41"
tracing-subscriber = { version = "=0.3.19", features = ["fmt", "env-filter"] }
cpay-proto = { git = "https://github.com/cpay-dev/proto-rs", rev = "25434eaa228ee545e9a5af2d2adc92c051c5318e" }
tonic = { version = "=0.14.2", features = ["transport"] }
tower-http = { version = "=0.6.6", features = ["trace"] }
serde = { version = "=1.0.226", features = ["derive"] }
serde_json = "=1.0.145"
http = "=1.3.1"
app-config = { path = "../../lib/app-config" }
